### ISSUE TITLE
Expansion File found, validated - but XAPKReader.get() always yeilds `APKExpansionFile not found.`

### ISSUE THREAD

**Issue by andremalkine** [moust/phonegap-xapkreader#16]
Everything set up as directed, .obb is already in place, no matter what all calls to XAPKReader.get( ... ) result in the following error:

```
APKExpansionFile not found.
 java.lang.NullPointerException
  at org.apache.cordova.CallbackContext.sendPluginResult(CallbackContext.java:60)
  at org.apache.cordova.xapkreader.XAPKReader$2.run(XAPKReader.java:94)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:841)

```

**Comment by JohnWeidner** [comment]
Please mention the xapkreader.xml in the documentation.

**Comment by JohnWeidner** [comment]
I'm updating the xapkreader.xml file with the new value.   But then when I do a build the old values get appended to that file.
